##DATABASE
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: floristeria

##SERVER
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

##EMAIL
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: grupoblomst@gmail.com
EMAIL_PASSWORD: bjro hkgj gknc jwzw
VERIFY_EMAIL_HOST: http://localhost:8080

##JSON --pasar el SECRET como variable de entorno
JWT_EXPIRATION: 432_000_000
JWT_SECRET: jQ57E3bV5Jhl3GZ7k8jA8WXNq7L3rT7q9Hp8MmVfZHqxjB5yY28UL0Gp6X5j3T9DkgV3r5+KmR9l1mQ=
